package TME4.Exo1;


/**
* TME4/Exo1/CalculHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculatrice.idl
* mercredi 20 mars 2013 16 h 47 CET
*/

abstract public class CalculHelper
{
  private static String  _id = "IDL:TME4/Exo1/Calcul:1.0";

  public static void insert (org.omg.CORBA.Any a, TME4.Exo1.Calcul that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static TME4.Exo1.Calcul extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (TME4.Exo1.CalculHelper.id (), "Calcul");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static TME4.Exo1.Calcul read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CalculStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, TME4.Exo1.Calcul value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static TME4.Exo1.Calcul narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof TME4.Exo1.Calcul)
      return (TME4.Exo1.Calcul)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      TME4.Exo1._CalculStub stub = new TME4.Exo1._CalculStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static TME4.Exo1.Calcul unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof TME4.Exo1.Calcul)
      return (TME4.Exo1.Calcul)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      TME4.Exo1._CalculStub stub = new TME4.Exo1._CalculStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
