package TME4.Exo3;

/**
* TME4/Exo3/HachageHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hashMap.idl
* mercredi 27 mars 2013 18 h 00 CET
*/

public final class HachageHolder implements org.omg.CORBA.portable.Streamable
{
  public TME4.Exo3.Hachage value = null;

  public HachageHolder ()
  {
  }

  public HachageHolder (TME4.Exo3.Hachage initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TME4.Exo3.HachageHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TME4.Exo3.HachageHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TME4.Exo3.HachageHelper.type ();
  }

}
