package TME4.Exo1.CalculPackage;


/**
* TME4/Exo1/CalculPackage/NotZero.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculatrice.idl
* mercredi 20 mars 2013 16 h 47 CET
*/

public final class NotZero extends org.omg.CORBA.UserException
{
  public String s = null;

  public NotZero ()
  {
    super(NotZeroHelper.id());
  } // ctor

  public NotZero (String _s)
  {
    super(NotZeroHelper.id());
    s = _s;
  } // ctor


  public NotZero (String $reason, String _s)
  {
    super(NotZeroHelper.id() + "  " + $reason);
    s = _s;
  } // ctor

} // class NotZero
