package TME4.Exo3;


/**
* TME4/Exo3/HachageOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hashMap.idl
* mercredi 27 mars 2013 18 h 00 CET
*/

public interface HachageOperations 
{
  boolean containsKey (String key);
  org.omg.CORBA.Object get (String key);
  void put (String key, org.omg.CORBA.Object value);
} // interface HachageOperations
