package TME4.Exo3;


/**
* TME4/Exo3/Hachage.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hashMap.idl
* mercredi 27 mars 2013 18 h 00 CET
*/

public interface Hachage extends HachageOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hachage
