package TME4.Exo1;


/**
* TME4/Exo1/CalculOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculatrice.idl
* mercredi 20 mars 2013 16 h 47 CET
*/

public interface CalculOperations 
{
  double add (double x, double y);
  double sub (double x, double y);
  double mult (double x, double y);
  double div (double x, double y) throws TME4.Exo1.CalculPackage.NotZero;
} // interface CalculOperations
