package TME4.Exo1;


/**
* TME4/Exo1/Calcul.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculatrice.idl
* mercredi 20 mars 2013 16 h 47 CET
*/

public interface Calcul extends CalculOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Calcul
