package TME4.Exo1;

/**
* TME4/Exo1/CalculHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculatrice.idl
* mercredi 20 mars 2013 16 h 47 CET
*/

public final class CalculHolder implements org.omg.CORBA.portable.Streamable
{
  public TME4.Exo1.Calcul value = null;

  public CalculHolder ()
  {
  }

  public CalculHolder (TME4.Exo1.Calcul initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TME4.Exo1.CalculHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TME4.Exo1.CalculHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TME4.Exo1.CalculHelper.type ();
  }

}
